name: Atualização do AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código-fonte
        uses: actions/checkout@v3  
      
      - name: Instala o Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Login no Azure CLI
        uses: azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Configuração do ambiente Azure CLI
        run: |
          az account set --subscription ${{ secrets.SUBSCRIPTION_ID }} 

      - name: Atualização do cluster AKS
        run: |
          az aks update -n cluster-flying-anteater -g rg-famous-ladybug --yes

      - name: Build da nova imagem
        run: |
          docker build -t ffelixtrc/vote-front:latest .
          docker push ffelixtrc/vote-front:V2
          docker build -t ffelixtrc/vote-back:latest .
          docker push ffelixtrc/vote-back:V2

      - name: Atualização do manifesto Kubernetes
        run: |
          sed -i 's|image:.*|image: ffelixtrc/vote-front:V2|' deploy.yaml
          sed -i 's|image:.*|image: ffelixtrc/vote-back:V2|' deploy.yaml
          kubectl apply -f deploy.yaml
